Bundle "scrooloose/syntastic"
Bundle "godlygeek/tabular"
Bundle "nono/vim-handlebars"
Bundle "tpope/vim-markdown"
Bundle "xsbeats/vim-blade"
Bundle "docteurklein/php-getter-setter.vim"
Bundle "altercation/vim-colors-solarized"
